name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Install deps
        run: npm install
      # Run test before deployemnt on surge
      - name: Run tests
        run: npm run test
      # Make a react app build for deployment on surge
      - name: Build React App
        run: CI=false npm run build # CI=false to ignore warnings

      - name: Install Surge
        run: npm install -g surge
        # Deploy to surge
      - name: Deploy to Surge
        run: surge ./build https://react-typescript-timer.surge.sh/ --token ${{secrets.TOKEN}}
